### ISSUE TITLE
Empty claims are not correctly parsed

### ISSUE THREAD

**Issue by miken32** [lcobucci/jwt#1072]
When trying to parse a JWT with an empty claims section, an error is thrown. I can't see anything in the RFC that prohibits such a structure:

>[4](https://datatracker.ietf.org/doc/html/rfc7519#section-4).  JWT Claims
>...
>The set of claims that a JWT must contain to be considered valid is context dependent and is outside the scope of this specification. Specific applications of JWTs will require implementations to understand and process some claims in particular ways.

>[10.3.1](https://datatracker.ietf.org/doc/html/rfc7519#section-10.3.1).  Registry Contents
>...
>Encoding considerations: 8bit; JWT values are encoded as a series of base64url-encoded values (some of which may be the empty string) separated by period ('.') characters.

Not sure how involved this change would be, so I'm not submitting a PR. But I was able to work around this in local code by simply removing the check/throw in `Lcobucci\JWT\Token\Parser::parse()` and then in `Lcobucci\JWT\Token\Parser::parseClaims()` setting `$data` to `W10` (i.e. encoded '[]') if it's the empty string.

**Comment by SvenRtbg** [comment]
Can you maybe illustrate what an example token would look like?

I'm looking at the code and fail to understand how anyone would consider a token that is either lacking the header, the body, or the signature part valid, or validatable. The header seems to be required to indicate what algorithm was being used for signing. The body might be able to be empty, but what use case would that present? The least amount of data in the body should be `{}`, i.e. the base64-encoded string cannot be empty. And finally, without a signature, the only defined algorithm for such a token would be "none", and that unfortunately has a history of security issues due to non-careful consideration in implementing libraries.

**Comment by miken32** [comment]
I'm building an ACME server for internal use, the specification describes requests without any claims as "POST-as-GET" requests. 

>[6.3](https://datatracker.ietf.org/doc/html/rfc8555/#section-6.3).  GET and POST-as-GET Requests
>...
>If a client wishes to fetch a resource from the server (which would otherwise be done with a GET), then it MUST send a POST request with a JWS body as described above, where the payload of the JWS is a zero-length octet string.  In other words, the "payload" field of the JWS object MUST be present and set to the empty string ("").

**Comment by miken32** [comment]
>The least amount of data in the body should be {}, i.e. the base64-encoded string cannot be empty.

Except the RFC explicitly says the body _can_ be empty.

**Comment by SvenRtbg** [comment]
JWS isn't identical to JWT, and that difference seems to be important here.

**Comment by miken32** [comment]
I'm a bit unclear on the relationship between all these specifications; at least JWT and JWS seem to overlap considerably. But the quotes in my initial report which allow for empty strings are from the JWT RFC, not JWS.

**Comment by SvenRtbg** [comment]
Indeed, JWS seems to be the broader standard here, allowing arbitrary content as the payload, while JWT specifies that content to be JSON itself, which may use some registered claims and allows for arbitrary add-ons.

This library deals with JWT. I doubt it can be made useful for a JWS use case, as the main issue with JWT at least, but probably with the entire set of JWx things is the amount of attacker-defined data that has to be validated.

In order to keep the amount of possible "developers shooting their own foot" situations to a minimum, this library makes no compromise during validation. And as detailed, JWT has an incompatible set of rules compared to JWS.

**Comment by lcobucci** [comment]
The JWT spec extends the JWS spec, providing rules for what will be in the JWS protected headers and the JWS payload.

> But the quotes in my initial report which allow for empty strings are from the JWT RFC, not JWS. 

The quoted content mentions empty claims, which are properties of the json object used as JWS payload in a JWT. 

Also, the bit about empty strings on the JWT encoded form is related to empty signatures (which is what happens when the "none" algorithm is used). 

As @SvenRtbg mentioned, this lib focuses on JWTs. However, its building blocks should give you some structure for handling JWS with random payloads.

**Comment by lcobucci** [comment]
Something like this should work for signing stuff (I wrote it on my mobile and haven't tested):

```php
function signContent(Encoder $encoder, Signer $signer, Key $key, string $content = '', array $headers = []): string
{
    $headers['alg'] = $signer->algorithmId();

    $encodedHeaders = $encoder->base64UrlEncode($encoder->jsonEncode($headers));
    $encodedContent  = $encoder->base64UrlEncode($content);

    $signature        = $signer->sign($encodedHeaders . '.' . $encodedContent, $key);
    $encodedSignature = $this->encoder->base64UrlEncode($signature);

    return $encodedHeaders . '.' .  $encodedContent . '.'  $encodedSignature;
} 
```

**Comment by miken32** [comment]
I don't need to sign anything, only verify stuff coming in from the clients. I will extend the parser class, since it will only be a few lines.

Edit: `final class`? 😓
