### ISSUE TITLE
Set default branch to 3.2

### ISSUE THREAD

**Issue by greg0ire** [lcobucci/jwt#114]
By default, people should use stable software, which means the readme they see should be the one of branch 3.2 . Also, people contributing will also probably want to contribute on this branch in most cases. Would you consider setting this branch as default one in the repo settings?

**Comment by lcobucci** [comment]
@greg0ire I don't plan to add new features on `3.2` (only bug fixes) that's why `master` is the default branch. However I do agree that it's annoying that the documentation is not pointing to last stable version.

My plan is to extract the documentation to the `doc` folder on `master` and maintain a gh page with the documentation for both `v3` and `v4` (#37).

Maybe you could help us to achieve this by sending a PR?

**Comment by greg0ire** [comment]
> Maybe you could help us to achieve this by sending a PR?

Sorry, I'm not involved enough with this piece of software to do that.
