### ISSUE TITLE
PKCS#8 compatibility

### ISSUE THREAD

**Issue by kotarCreative** [lcobucci/jwt#149]
Does your library support the use of .p8 files for the storing of private keys? Looking to use this to implement the new token format for Apples push notifications.

**Comment by lcobucci** [comment]
@kotarCreative this library uses `openssl` extension to handle RSA signature and as far as I saw that extension doesn't support PKCS8 files, so you have two options:

1. Extract the private and public keys from the `.p8` file (`.p8` -> `.pem` -> `.key` pair), maybe [this](http://www.commandlinefu.com/commands/view/135/convert-a-pkcs8-private-key-to-pem-format) can help you.
1. Implement your own signer that offers support for that kind of file. As @Ocramius said, the lib itself just requires a `Key` to be passed around so you can create something to that does what you need (I think that phpseclib can help you).

If you decide to go with the second option I'd suggest to create a small library that depends on this one since I plan to extract all the signers to their own repositories (some day 😜).

**Comment by lcobucci** [comment]
Closing as `wontfix` since the solution would not be made in the library.
