### ISSUE TITLE
Add optional parameter to _not_ escape forward slashes.

### ISSUE THREAD

**Issue by ikoene** [lcobucci/jwt#156]
*I'm not 100% sure this is a bug, but this seems the best place to question this.*

I'm working with the 3.2 release.

So I've basically encountered an inconsistency between libraries that create json web tokens. Our client uses [node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) to create a token. I needed to do the same on our side, so when I tried to create the web token using this library, I've found that the second part of the JWT payload differs and thus the provided secret by our client was not working. 

Here's a quick example of the payload:

```
[
  "url": "https://some-url",
  "iss": "https://some-other-url",
  "sub": "123456789",
  "aud": "123456789",
  "exp": 1484284311,
  "iat": 1484248311,
];
```

After a lot of research, we've found that the node-jsonwebtoken library *does _not_ escape the forward slashes in the url*, while this one does. When base64 encoding this json string, the second part of the json web token is incorrect.

So. What the consensus about this? Is there some kind of unwritten rule on how to encode (with/without escaping)? What's the correct one? If there's no rule, it could be useful to be able to add the optional parameter `JSON_UNESCAPED_SLASHES` for json encoding.

I've fixed it in my project by implementing the [Builder](https://github.com/lcobucci/jwt/blob/2.1/src/Builder.php) in a new, custom Builder class & injecting my own [encoder](https://github.com/lcobucci/jwt/blob/2.1/src/Parsing/Encoder.php) that DOES escape the slashes. My Encoder class is basically identical to the source, but differs here:

`$json = json_encode($data, JSON_UNESCAPED_SLASHES);`

**Comment by schnittstabil** [comment]
The signature is based on the payload. For example:
```php
signature := HMACSHA256(base64UrlEncode(header) + "." + base64UrlEncode(payload), secret)
```

Because of the different encoding, the second part of the JWT payload will differ; and therefore the signature must differ as well.

> I've found that the second part of the JWT payload differs and thus the provided secret by our client was not working.

As you were able to fix the problem using `JSON_UNESCAPED_SLASHES`, I assume that you tested the signature (third part of the JWT) for equality. But that's the wrong way to verify tokens. Instead you have to use the [verify method](https://github.com/lcobucci/jwt#token-signature):

```php
var_dump($token->verify($signer, $publicKey)); // true when the public key was generated by the private one =)
```

**Comment by lcobucci** [comment]
@ikoene as @schnittstabil explained even with different encoded content the library must be able to verify the signature because we keep the original data. This difference will happen but it doesn't mean that the token is necessarily invalid.

We do have tests that covers tokens generated by different libraries as you can see on https://github.com/lcobucci/jwt/blob/ddce703826f9c5229781933b1a39069e38e6a0f3/test/functional/RsaTokenTest.php#L258.

BTW I saw that the links you sent points to `v2.1` which is very outdated and not secure (it wasn't not protected against [this](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/)).

**Comment by lcobucci** [comment]
Closing as `invalid`.
