### ISSUE TITLE
Private properties are limiting.

### ISSUE THREAD

**Issue by michaeldnelson** [lcobucci/jwt#219]
This is not a bug, more of a question/request.  I have noticed a trend lately of making properties/methods private instead of protected.  It's possible I am out of the loop, and there is a good reason for this but it makes it very difficult for me to create nice apis for coding my domain.  I would like to implement convenient accessors for claims that have extended parsing logic.  $token->hasGroupFoo('bargroup') (where there is some extended parsing logic for determining foo).  I know of no convenient way to implement this using this library, I can't access several of the important properties in the parent, I cant extend builder to create my own tokens because of private properties in that class e.g. encoder.  My only choice is to basically reimplement this entire library for a simple accessor, use performance degrading reflection, or double function calls with multiple facades.  As I said maybe there is a really good reason for this as it seems all libraries are doing this now, but I would really like to have my accessor.

Thanks!

edit: I forgot to say thank you very much for this library, overall it is great and useful.  I would really just like to be able to extend without forking.

edit2:  I've just read a bunch on why people would declare something as final, seems like the general reasoning is someone might extend it and do something wrong or that people might not realize they need to lock their vendor dependencies if they are accessing object internals.  Maybe that makes sense if you are working with a team on banking software and not building a library for public consumption.  I would rather not copy paste a bunch of code just to build an accessor.

edit3:  A concrete example for more context: A OIDC IdToken is_a Token with accessors such as, getZoneInfo(), getBirthdate()

**Comment by lcobucci** [comment]
@michaeldnelson first of all, thanks for submitting this issue! It's always good to explain design decisions - and it can also be used as a topic for the upcoming documentation that needs to be written.

Let's go, then (brace yourself, it might be a long answer)! 

When designing packages (regardless if it is a project or library) we have to think about how it should be used and what are its extension points. Fortunately we have [principles to follow, not only regarding how to design classes but also packages](http://butunclebob.com/ArticleS.UncleBob.PrinciplesOfOod).

With the new API (provided in v4), I've decided to be **extremely explicit** regarding the intended usage of this library, which means (in a naive summary): defining proper abstractions and limiting people from using [unstable components](https://web.archive.org/web/20021107013916/http://www.objectmentor.com/resources/articles/oodmetrc.pdf).

That decision is definitely not a very easy one... we have to consider multiple things and I really wanted to achieve one thing: I don't want to allow people to inherit concrete classes of this library (which is exactly the limitation you're facing).

The reason is quite simple: I believe that nobody should extend classes provided in this package. Why? I believe that we should prefer composition over inheritance (yes, this is a very old and long discussion), mostly because every time we use inheritance we define an extremely couple association - which is absolutely fine for components we own, but IMO it could/should be avoided for 3rd party components.

So IMHO you should rather define your own OIDC id token, which decorates a `JWT` token and provides the additional behaviour you want, like:

```php
namespace MyPackage\OpenId
{
    interface IdToken
    {
        public function getZoneInfo(): ?string;
        public function getBirthdate(): ?string;
    
        // all other methods you might find useful...

        public function __toString(): string;
    }
}

namespace MyPackage\OpenId\IdToken
{
    use Lcobucci\JWT\Token\Plain;
    use MyPackage\OpenId\IdToken as IdTokenInterface;

    final class IdToken implements IdTokenInterface
    {
        /**
         * @var Plain
         */
        private $jwt;

        public function __construct(Plain $jwt)
        {
            $this->jwt = $jwt;
        }

        public function getZoneInfo(): ?string
        {
            return $this->jwt->claims()->get('zoneinfo');
        }

        public function getBirthdate(): ?string
        {
            return $this->jwt->claims()->get('birthdate'); // you can convert this to a \DateTimeImmutable but it's important to handle the case when year is `0000`...
        }

        public function __toString(): string
        {
            return (string) $this->jwt;
        }
    }
}
```

With this design you would be explicit regarding the behaviour of your id token, also your components would be decoupled from any 3rd party components (since everything would depend on the provided interface, reducing the implementation to a detail).

I understand that my decisions regarding the usage of `lcobucci/jwt` might not make everyone's life easier, but I think that libraries should NOT make **everything** easier - just some small bits (mostly because software development is definitely not easy at all)...

I hope this clarifies my intention and gives you a direction on how to extend and use this lib.

**Comment by michaeldnelson** [comment]
Hi @lcobucci,

Thank you for taking the time to respond to my issue.  The approach you are describing is what I meant by facade although decorator is certainly more correct as I am adding functionality not creating a new api.  It's interesting that you bring up SOLID principles as I would consider this a violation of the open closed principle.  I did in fact do just what you suggested, however you have to create a decorator for the builder as well so you can return tokens of your own type.  This is certainly more code than I was hoping for something so simple.  I also don't love that I am doubling function calls for something that will be checked on almost every request.  All that said it's your rodeo :) . I guess I disagree on principle with the notion that developers shouldn't be trusted.  All that said I would still rather use this library than the other ones out there so thanks!

Michael

**Comment by lcobucci** [comment]
>  It's interesting that you bring up SOLID principles as I would consider this a violation of the open closed principle.

@michaeldnelson not exactly... "Make all Member Variables Private" it's actually a recommended heuristic described in [the open-closed principle](https://drive.google.com/file/d/0BwhCYaYDn8EgN2M5MTkwM2EtNWFkZC00ZTI3LWFjZTUtNTFhZGZiYmUzODc1/view).

> however you have to create a decorator for the builder as well so you can return tokens of your own type. This is certainly more code than I was hoping for something so simple. I also don't love that I am doubling function calls for something that will be checked on almost every request.

That shouldn't be needed. I mean, in my opinion you could simply use the builder/parser and return the encapsulated token. Like:

```php
namespace MyPackage\OpenId;

use Lcobucci\JWT\Configuration;
use Lcobucci\JWT\Token;
use Lcobucci\JWT\Validation\Constraint;
use MyPackage\OpenId\IdToken;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Zend\Diactoros\Response;

final class AuthenticationMiddleware implements MiddlewareInterface
{
    /**
     * @var Configuration
     */
    private $jwtConfig;

    /**
     * @var Constraint[]
     */
    private $validationConstraints;

    public function __construct(
        Configuration $jwtConfig,
        Constraint ...$validationConstraints
    ) {
        // Ideally you should inject each needed object (to avoid hiding your
        // dependencies), but this is just an example...

        $this->jwtConfig             = $jwtConfig;
        $this->validationConstraints = $validationConstraints;
    }

    public function process(
        ServerRequestInterface $request, 
        RequestHandlerInterface $handler
    ): ResponseInterface {
        $jwt = $this->parseToken($request->getHeaderLine('Authorization'));

        if (! $this->validateToken($jwt)) {
            return new JsonResponse(['error' => 'You must send a valid token'], 401);
        }

        return $handler->handle(
            $request->withAttribute(IdToken::class, new IdToken\IdToken($jwt))
        );
    }

    private function parseToken(string $authorization): ?Token
    {
        if ($authorization === '') {
            return null;
        }

        $type  = substr($authorization, 0, 6);
        $token = substr($authorization, 7);
        
        if ($type !== 'Bearer' || $token === false || $token === '') {
            return null;
        }

        return $this->jwtConfig->getParser()->parse($token);
    }

    private function validateToken(?Token $token): bool
    {
        if ($token === null) {
            return false;
        }

        return $this->jwtConfig->getValidator()->validate(
            $token, 
            ...$this->validationConstraints
        );
    }
}
```

This simple middleware ensures that the token you're receiving respects the constraints you expect and only passes an instance of your `IdToken` to the next request handlers, so your application will never depend on a token from this library.

Obviously this is a very naive example and won't use the id token to authorise anything, that's why you have the access token, however this might be useful to give you some ideas on how to use the components of this lib.

> All that said it's your rodeo :) . I guess I disagree on principle with the notion that developers shouldn't be trusted. All that said I would still rather use this library than the other ones out there so thanks!

I'm glad you like it and I hope it's being useful for you, cheers!

**Comment by michaeldnelson** [comment]
Interesting read.  Maybe my eyes will be opened to the value of private/final after some practice, been a few years in python which is much more open.  You've obviously thought it through, I guess I'll see how it plays out :).  For clarity I decorate the builder for the initial issuing of the token not the middleware, something like $idTokenBuilder()->withZoneInfo($zone) .  The middleware plays out as you described.  Thanks again, sorry for taking so much of your time but really, thanks for all the replies.

**Comment by lcobucci** [comment]
Documentation added in #326
