### ISSUE TITLE
Getting claims from Token

### ISSUE THREAD

**Issue by JoeBengalen** [lcobucci/jwt#228]
Hi, I noticed that the `Plain` token has a [`claims` method](https://github.com/lcobucci/jwt/blob/master/src/Token/Plain.php#L49), but it's not part of the `Token` interface.

Is this missing on purpose? If not I could create PR to add it if you like.

```php
interface Token {
    public function claims(): DataSet;
}
```

**Comment by lcobucci** [comment]
@JoeBengalen it was made like that in purpose.

The general idea is that the token can either be encrypted or plain but only plain tokens have readable claims, and since the token you receive is already something that cannot really be trusted (user input) you have to be explicit regarding your expectations. Like:

```php
$token = $parser->parse($jwtFromSomewhere);

if (! $token instanceof Plain) {
    throw new \RuntimeException('NOPE!');
}
```

Sure that's a very basic validation but you could rely on our new validator to do what you want and simply use [`assert()`](https://secure.php.net/manual/en/function.assert.php) to be IDE friendly (please remember that ideally `zend.assertions` should be set to `-1` in production environment), like:

```php
$token = $parser->parse($jwtFromSomewhere);
assert($token instanceof Plain);

if (! $validator->validate($token, ...$myConstraints)) {
    throw new \RuntimeException('NOPE!');
}

// $token->claims() will be available here
```

We don't support JWE yet but this was designed as a forward compatibility layer for future implementation.

---

Please don't forget that `v4.0` is not stable yet and the public interface will still suffer some minor changes - thanks you for trying it out, though!

**Comment by lcobucci** [comment]
Linking #203 and #186

**Comment by lcobucci** [comment]
@JoeBengalen please let me know if that offers you enough information!

**Comment by JoeBengalen** [comment]
Yes, thank you. I could've done a search on previous issues maybe :sweat_smile:

**Comment by lcobucci** [comment]
@JoeBengalen sorry for my delay on getting back to you, my idea is to release a new alpha of v4 in a week or two. I'll organise the milestones ASAP to ensure that things make more sense 👍
