### ISSUE TITLE
How to install gmp extension for php 7.2.1 using MAMP on OSX?

### ISSUE THREAD

**Issue by lloydkeijzer** [lcobucci/jwt#238]
> How to install gmp extension for php 7.2.1 using MAMP on OSX?

I'm trying to encrypt a token using the Elliptic Curve Digital Signature Algorithm (ECDSA) with the P-256 curve and the SHA-256 hash algorithm.

**error when running php script:**
```

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Mdanter\Ecc\EccFactory' not found
```

I figured that I'm missing the mdanter/ecc dependicy package, so I tried running the following command.

**command running:**

`composer require mdanter/ecc:~0.3.1`

**output:**

`mdanter/ecc v0.3.1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system`

I've tried everything I could find researching this error and related to MAMP. But I couldn't solve this problem. **Is there anyone here who has experience in adding the gmp php extension to MAMP specificly and is willing to help me out?**

Note: I'm not a very experienced web developer, I mostly create iOS apps and I want to generate a token in php, so I can access the Apple Music Kit API resources.

**Comment by Ocramius** [comment]
Closing here: while this may well be related to the repo, installing `ext-gmp` in the specific context of MAMP is out of scope for this repo.

My general suggestion (from previous experience with MAMP) is to kill MAMP with fire, and use a much simpler built-in setup with something like homebrew and with the built-in PHP server (`php -S localhost:8080`), since homebrew comes with the most common extensions.

Otherwise `pecl` should do the trick.

**Comment by markuspoerschke** [comment]
The question is answered here: https://stackoverflow.com/questions/50435455/how-to-install-gmp-extension-for-php-7-2-using-mamp-on-osx
