### ISSUE TITLE
Undefined method SplFileObject::fread()

### ISSUE THREAD

**Issue by taasan** [lcobucci/jwt#256]
Commit 8e80bec6ad37421b93e1e9b088fbf3767ab6840b introduced an error on PHP 5.5.9 (which I am stuck at)

```PHP Fatal error:  Call to undefined method SplFileObject::fread() in /var/www/vendor/lcobucci/jwt/src/Signer/Key.php on line 66```

**Comment by Ocramius** [comment]
I don't think that we should fix bugs for EOL'd PHP versions, so I'm closing as `won't fix` here, sorry.

**Comment by taasan** [comment]
Well, you should at least update composer.json with minimum php version 5.5.11 for this version so you don't lie about which php version is needed.

**Comment by Ocramius** [comment]
True that. @lcobucci what's your opinion on that? Reopen and fix? EOL our
version?

**Comment by lcobucci** [comment]
@taasan I'm very sorry for that issue, it's been like ages since I use that version of PHP that I completely forgot about it. Making the change compatible with your PHP version is so simple that I rather modify the library. But please try to upgrade your stack as soon as possible, v3.3 will require PHP 5.6 and v4 PHP 7.2 (possibly 7.3)

**Comment by taasan** [comment]
Thanks :-) I am unfortunately stuck with Ubuntu 14.04 for another year
