### ISSUE TITLE
I want validate Many Issuer

### ISSUE THREAD

**Issue by acodercat** [lcobucci/jwt#265]
I want validate Many Issuer
e.g ['issuer1', 'issuer2']

**Comment by Ocramius** [comment]
Seems to be feasible on `master`: https://github.com/lcobucci/jwt/blob/master/src/Validation/Constraint/IssuedBy.php

**Comment by Ocramius** [comment]
Yep, verified: on `3.x`, this isn't really working due to expected equality: https://github.com/lcobucci/jwt/blob/c9704b751315d21735dc98d78d4f37bd73596da7/src/Claim/Factory.php#L39

On 4.x, this will work via the constraint I linked (https://github.com/lcobucci/jwt/blob/13ada5bd47c27d9eb2cd382fbc1a10437f6000af/src/Validation/Constraint/IssuedBy.php)

**Comment by Spomky** [comment]
Additionally, it deviates from the specification. The [`iss` claim](https://tools.ietf.org/html/rfc7519#section-4.1.1) is supposed to be a string (or URI).
For this specific case, best would be to use a custom claim.

**Comment by lcobucci** [comment]
@Spomky the `iss` claim is indeed a single string but your application can allow multiple issuers when validating, which is exactly @acodercat's need.

**Comment by Spomky** [comment]
OK. I thought he wanted to validate a token with the `iss` claim containing a list of issuers instead of a string.
