### ISSUE TITLE
Secret key to HS256 token not working

### ISSUE THREAD

**Issue by rishabhchd19** [lcobucci/jwt#299]
Hi,

I want to generate ENCRYPTED token with the Header + Payload + Signature as shown in the image, but I want to keep the red marked box unchecked. To Generate that I used the following syntax for "alg": "HS256",  "typ": "JWT" as shown below:

```php
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;

$user=array("name"=>$admin_name,"avatar"=>"https://teleconf.yogdiagnostics.com/images/company_avatar.png", "email"=>$admin_email,"id"=>"yd-12345-abcde");
$context=array("user"=>$user,"group"=>" * ");
$signer = new Sha256();
$admin_token =(new Builder())->set('context',$context)
						->setAudience(' * ')
						->setIssuer('yd-12345-abcde')
                                                ->setSubject('teleconf.yogdiagnostics.com')
						->set('room',strval($room))
						->setExpiration(time()+$exp)
						->setHeader("alg","HS256")
						->sign($signer, '@bcde')
						->getToken();
```

But the Authentication is not working. Have I done anything incorrect? What will be the syntax to generate the token for the payload & secret key as shown in the image?

![3](https://user-images.githubusercontent.com/30948461/59128347-6c2d2900-8987-11e9-894c-ff18f55f4b12.jpg)

**Comment by rishabhchd19** [comment]
@Ocramius can you please help me solving this issue. I shall be thankful to you.

**Comment by lcobucci** [comment]
@rishabhchd19 that's a bit odd... Just to understand it properly, you *don't want* to use a base64 encoded string as key, right? And is there any chance you mistyped something? On your snippet you're using `@bcd` as key and `@bcde` on the screenshot...

**Comment by rishabhchd19** [comment]
Hi @lcobucci ....yes key is same but I don't want key to be used as secret base64 encoded. Is it the right syntax am I using to generate the token as same as shown in image? Also, what's the difference in $signer, '@bcde' and $signer, new Key('@abcde') ?

**Comment by lcobucci** [comment]
>  Is it the right syntax am I using to generate the token as same as shown in image? 

@rishabhchd19 you're issuing the token in the correct way.

This snippet below is the same as yours but with the missing variables:

```php
require 'vendor/autoload.php';

use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;

$admin_name = 'Test';
$admin_email = 'test@test.com';
$room = 'Testing';
$exp = 3600;

$user = array("name"=>$admin_name,"avatar"=>"https://teleconf.yogdiagnostics.com/images/company_avatar.png", "email"=>$admin_email,"id"=>"yd-12345-abcde");
$context = array("user"=>$user,"group"=>" * ");
$signer = new Sha256();
$admin_token = (new Builder())->set('context',$context)
                              ->setAudience(' * ')
                              ->setIssuer('yd-12345-abcde')
                              ->setSubject('teleconf.yogdiagnostics.com')
                              ->set('room',strval($room))
                              ->setExpiration(time() + $exp)
                              ->setHeader("alg","HS256")
                              ->sign($signer, '@bcde')
                              ->getToken();

echo $admin_token, PHP_EOL;
```

Running it now generates the token: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsibmFtZSI6IlRlc3QiLCJhdmF0YXIiOiJodHRwczpcL1wvdGVsZWNvbmYueW9nZGlhZ25vc3RpY3MuY29tXC9pbWFnZXNcL2NvbXBhbnlfYXZhdGFyLnBuZyIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlkIjoieWQtMTIzNDUtYWJjZGUifSwiZ3JvdXAiOiIgKiAifSwiYXVkIjoiICogIiwiaXNzIjoieWQtMTIzNDUtYWJjZGUiLCJzdWIiOiJ0ZWxlY29uZi55b2dkaWFnbm9zdGljcy5jb20iLCJyb29tIjoiVGVzdGluZyIsImV4cCI6MTU2MDA3Nzk4NX0.sFYHQEoR0sqrM_rCwErXBSPqP-ODggitR4D2xaAqYu8`

Putting such token in jwt.io, **after configuring the expected key to be used for validation**, gives us the following result:

![Screenshot from 2019-06-09 12-00-52](https://user-images.githubusercontent.com/201963/59157641-45b5dd80-8aae-11e9-8c89-6d8380772271.png)

It's important to set the key before of pasting the token in jwt.io. Otherwise, that tool modifies the signature of the token to always match the key - and will always say that the signature is verified.

Example with invalid key:

![Screenshot from 2019-06-09 12-03-05](https://user-images.githubusercontent.com/201963/59157661-9f1e0c80-8aae-11e9-8e54-31ed59197f69.png)

> Also, what's the difference in $signer, '@bcde' and $signer, new Key('@bcde') ?

`new Key('@bcde')` is the way we're planning for the future (v4.0.0). However, in order to not break BC, we allow both old and new ways to pass the key and the token builder checks which one is being used and ensures that things are correct.

**Comment by rishabhchd19** [comment]
Ok. Thank You very much @lcobucci ....I will check it at my system end. Your help means alot to me as it will make easy for me to debug the actual problem.

**Comment by lcobucci** [comment]
@rishabhchd19 just saw this bit now:

> I want to generate ENCRYPTED token with the Header + Payload + Signature as shown in the image

[Encrypted token is something slightly different](https://tools.ietf.org/html/rfc7519#page-26), are you sure you need this? This lib doesn't support encrypted tokens (neither does jwt.io).

If you do have the need for encrypted/nested tokens then you should checkout out @Spomky's awesome JWT framework https://web-token.spomky-labs.com/v/v2.x/

**Comment by rishabhchd19** [comment]
> are you sure you need this?

No...I just wanted as same as shown in the Image...I think the syntax you suggested above will resolve the issue...because syntax was fine, now i will see into the system. :)

**Comment by lcobucci** [comment]
@rishabhchd19 alright, I'll close this issue for now then. Feel free to reopen it if need help :+1:
