### ISSUE TITLE
help for rest api and jwt

### ISSUE THREAD

**Issue by flihub** [lcobucci/jwt#302]
i read a lot of jwt tutorials but i have some still questions ? 

1. we wanted to write a mobile api, allow only mobile app user with username and password info to access api. 
And we build a login page user profile.
So we should give jwt only to mobile api user ? 
After User login we not give token ? 

2.  After user login mobile app should save username password to somewhere, or should save user jwt ( if we give jwt for every user ).  

After jwt expire what should we do?  
Can we extend expire old token and give a new token, or we should ask to username and password again?

**Comment by lcobucci** [comment]
@flihub I'm sorry that I took longer to get back to you than on this you expected, and hope you managed to find the answers you were looking for.

If you didn't find, let's see if I can still help...

The interesting thing about the specs is that they don't exactly tell you how to use JWT, leaving it up to developers to think about their use case and see if it's applicable or not. This library does the same, our scope is issuing, parsing, and validating JWTs.

When using JWTs for APIs, it's common to issue a token for every authenticated user. Depending on the needs, this token can be an one time token or it can last for a few minutes (there are pros and cons to both situations).

Some people might issue a refresh token together with the access token, so that a new token pair can be generated without the need for the password (which should never be stored in the application IMHO).

JWTs are immutable, so you don't really extend it, you issue a new one.

If you prefer not to think too much about all the possible ways of doing API authentication and need to also handle client authorisation, maybe OAuth2 is a good idea (you can use JWTs as the bearer access token https://oauth.net/2/jwt/).

**Comment by flihub** [comment]
thank u:)

if i use a refresh token, how to generate ?  
refresh can be as like jwt ? 

and how i know token is access or refresh ? should i include a token type in payload data?

**Comment by lcobucci** [comment]
@flihub that really depends on your needs. For example, if you also want to have data in the refresh token and want for it to expire, then you can definitely use a JWT. Otherwise, an opaque string should do it. 

Usually the access token goes in a header or cookie, the refresh token is only send (via request body) to the endpoint that refreshes the "session". 

Check out the OAuth2 RFC to understand how that's solved there.
