### ISSUE TITLE
Allow globally configurable default skew leeway

### ISSUE THREAD

**Issue by soundsgoodsofar** [lcobucci/jwt#308]
Recently updated and noticed that an ability to set leeway for clock skew was added in https://github.com/lcobucci/jwt/pull/248/files

That's great (thanks), but I'd like to ask that the default value is made configurable through a global constant static method.  The reality is that this package is a fairly deep downstream dependency for a lot of people.  I could start the process to convince league/oauth2-server to support the setting, and then start convincing laravel/passport to support it, but it's just not worth the time.

Personally I've just updated my previous composer post-install patch to:

    --- a/vendor/lcobucci/jwt/src/ValidationData.php
    +++ b/vendor/lcobucci/jwt/src/ValidationData.php
    @@ -34,7 +34,7 @@
          * @param int $currentTime
          * @param int $leeway
          */
    -    public function __construct($currentTime = null, $leeway = 0)
    +    public function __construct($currentTime = null, $leeway = 120)
         {
             $currentTime  = $currentTime ?: time();
             $this->leeway = (int) $leeway;

It would be a bit cleaner if instead I could just make a call like:

    Lcobucci\JWT\ValidationData::setDefaultLeeway(120);

Best

**Comment by lcobucci** [comment]
@soundsgoodsofar thanks for sharing your idea!

`v4` (available for tests) introduces a brand new validation component, where you can create a set of global constraints and even provide your custom constraints - depending on how other libs and frameworks use it, sure. I'm slowly porting some features from `v4` to `v3`, creating a migration path to the new version.

With that said, I'd suggest to wait for `3.4.0` and rely on the new API - especially because it involves coordination with multiple packages. Then we can let the old validation methods die a terrible death :smile: 

On your proposal, I **really** dislike the added confusion that using static methods like bring to the application. However, I wouldn't be opposed to it as long as **we all understand that it will be born with an expiration date**.

**Comment by soundsgoodsofar** [comment]
Yep I totally agree it's not elegant.  It's only a bit more elegant than patching files to fix it for people who have no immediate solution.  What you're describing sounds great, but as these things go there will be people who can't upgrade any time soon for practical or political reasons.

**Comment by lcobucci** [comment]
We're will be backporting the new validation API on #510, which solves this issue.
