### ISSUE TITLE
Should Builder contains Signer & Key?

### ISSUE THREAD

**Issue by jakubboucek** [lcobucci/jwt#338]
This issue is related to current version in `master` branch and [current doc for **Issuing Tokens**](https://lcobucci-jwt.readthedocs.io/en/latest/issuing-tokens/).

Related code is:
```php

$configuration = Configuration::forSymmetricSigner(
    new Sha256(),
    new Key('mBC5v1sOKVvbdEitdSBenu59nfNfhwkedkJVNabosTw=')
);

$token = $config->createBuilder()
                ->issuedBy('http://example.com')
                // ...
                ->getToken($config->getSigner(), $config->getSigningKey());
```

I't make impossible to use `Builder` simply as service to DI container, because I need above that the `Configuration` service to get `Key` &  `Signer`. 

In use case in app sound as greate flow to get prepared instance of `Builder` with few system-wide claims and allow to add custom claims and than convert to the token. This interface here required to get pair of cooperating services (configurator + prepared `Builder`) or create custom new envelope object which contains both of them and copy-provide their interface for better integration with simple DI services design.

I understanding it great for tests and clean design. But maybe should be better to refactor `Builder` and split their internal implementation to `ClaimsBuilder` and `SignBuilder` and keep basic `Builder` with simple interface like in version `v3.3`.

My suggest is:
- rename `Builder` to `ClaimsBuilder`,
- create `SignBuilder`,
- create `Builder` with simple interface for better support use DI design.

Is my things correct or I am blind at any stage?

**Comment by lcobucci** [comment]
@jakubboucek thanks for your input :+1: 

The builder implements the builder design pattern, which makes it stateful. Putting it as a DI service wouldn't be appropriated IMHO because it would require you to mark it as a non-shared service - only available in a few DI container components.

The idea is that the configuration object should be set as a DI service, allowing you to reuse things as you please while keeping the cohesion of the builder API. It also makes things easier for test suites, since one can use a faster algorithm for tests (or even no algorithm) and not affect the system.

Does this clarify things?

**Comment by lcobucci** [comment]
Closing here since we didn't get any input from @jakubboucek
