### ISSUE TITLE
Why  a Lcobucci\JWT\Signer\Key accepts a null argument ?

### ISSUE THREAD

**Issue by athoune** [lcobucci/jwt#362]
An empty string is logic, but a  nullable `$content`, like an undefined variable, should raise an exception.

[RFC recommends 128 bits as minimum key size](https://tools.ietf.org/html/rfc7515#section-10.1), why `Lcobucci\JWT\Builder::getToken` doesn't enforce that, with an exception for the dreaded **none** signer?

**Comment by lcobucci** [comment]
> An empty string is logic, but a nullable $content, like an undefined variable, should raise an exception.

@athoune the current stable version is compatible with PHP 5 so we couldn't use scalar types on the signature - you can see that it's not the case for the  PHP 7.4+ alpha version: https://github.com/lcobucci/jwt/blob/master/src/Signer/Key.php#L20.

No exception was added because, back then, I thought that people wouldn't actually use `null` for the key.

> RFC recommends 128 bits as minimum key size, why `Lcobucci\JWT\Builder::getToken` doesn't enforce that, with an exception for the dreaded none signer?

The `Key` object works for different algorithms and enforcing a minimum length for the (HMAC) key isn't really a responsibility of `Lcobucci\JWT\Builder::getToken`.
Since it's a recommendation and not a requirement, I opted not to enforce it.

**Comment by lcobucci** [comment]
I hope this provides clarity :+1: 
Will close this one but feel free to comment/re-open!
