### ISSUE TITLE
Method to extract payload?

### ISSUE THREAD

**Issue by robksawyer** [lcobucci/jwt#40]
Does it make sense to have a helper method that extracts the payload claims that don't include: iss, aud, jti, iat, nbf, exp? Something like the following:

```
$token->getPayload(); // Retrieves the custom claims

//Instead of having to do
$uid = (string) $token->getClaim('id');
$custom = (string) $token->getClaim('custom');
```

**Comment by lcobucci** [comment]
@robksawyer sorry but I think this wouldn't improve things. Never saw anyone needing this. Can you provide more information in order to open my eyes to it?

Btw, you can easily achieve this with [array_intersect_key()](http://php.net/manual/en/function.array-intersect-key.php)/[array_diff_key()](http://php.net/manual/en/function.array-diff-key.php) and [array_map()](http://php.net/manual/en/function.array-map.php):

Would be something like this:
```php
$convert = function (\Lcobucci\JWT\Claim $claim) {
    return $claim->getValue();
};

$desiredClaims = ['custom' => null];
var_dump(
    array_map($convert, array_intersect_key($token->getClaims(), $desiredClaims));
);

// OR

$claimsToRemove = ['jti' => null, 'iat' => null];
var_dump(
    array_map($convert, array_diff_key($token->getClaims(), $desiredClaims));
);
```

**Comment by robksawyer** [comment]
This was before I realized that I could pass objects to the set method.
Sorry to bug.

**Comment by lcobucci** [comment]
Ok, closing this!
