### ISSUE TITLE
$data->setCurrentTime?

### ISSUE THREAD

**Issue by robksawyer** [lcobucci/jwt#41]
Can you elaborate on why you're doing the following? I'm a bit confused. Shouldn't I be able to validate the token using `$data->setCurrentTime(time());`? Based on the current vs. the expiration time.

```
$data->setCurrentTime(time() + 4000); // changing the validation time to future
```

**Comment by lcobucci** [comment]
Hello @robksawyer, sorry about my huge delay to answer you (many things going on :smile:).

The ```$data->setCurrentTime()``` is being called in the example for documentation purposes and you should not call it (if you read carefully you'll see the lines above and bellow the invocation in README you'll see that the reason is fail at the second time).

In ```ValidationData::__construct()``` the current time is already being configured with ```time()```.

I'm online right now on [gitter](https://gitter.im/lcobucci/jwt) we can have words there if you want.

**Comment by robksawyer** [comment]
I didn't read carefully. Noticed this shortly after I posted.

**Comment by lcobucci** [comment]
Ok I'll close this.
