### ISSUE TITLE
What if I need only parse and verify tokens without issuing with v4?

### ISSUE THREAD

**Issue by XAKEPEHOK** [lcobucci/jwt#609]
As I can see, I cant configure Configuration::forAsymmetricSigner() with null signing key, but why? I have two apps, first app issuing tokens and sign its with Rsa\Sha512 and also share public key by fixed http uri. Second app receive tokens from first app, trying to download public key and want verify that token was issued and signed by first app. Second app dont want issuing tokens, only verifying. How I can configure your Configuration object for that?

**Comment by t0mmy742** [comment]
If you look at [Configuration::forUnsecuredSigner](https://github.com/lcobucci/jwt/blob/76734640d36383432b02bc09fd2f97edcc1b278e/src/Configuration.php#L83) method, you can see `Key` object instancied with `InMemory::empty()`.
You can't use a null key, you need a `Key` object. But you can use an "empty" signing key, because you do not need it for validation. For your `Configuration::forAsymetricSigner` function, let's give `InMemory::empty()` as a second arguments.

**Comment by XAKEPEHOK** [comment]
t0mmy742, looks good. Thanks!
