### ISSUE TITLE
Create JWT without verification key

### ISSUE THREAD

**Issue by SamMousa** [lcobucci/jwt#620]
I'm using JWTs for SSO.
Using asymmetric signatures means that one system is creating a JWT and another is verifying it.
In the code samples for v4 there is no way to create a configuration object without passing it both a signature AND a verification key.

**Comment by SamMousa** [comment]
I've worked around it by not using the configuration object which to me seems to serve no purpose.

**Comment by Slamdunk** [comment]
The configuration is useful to split apart config ad usage times.

You're right it's not very clear, by the way the verifier should use `\Lcobucci\JWT\Signer\Key\InMemory::empty()` as the signature key.

**Comment by SamMousa** [comment]
The `Configuration` class is not a very useful thing though. It combines dependency, thereby making them less obvious.
It is also a factory for the `Builder` class, which means it has multiple responsibilities.
To make it even less useful, when it creates the builder class it doesn't even inject the configuration (like signer and keys).

In my opinion the `Configuration` object muddies the design.

> You're right it's not very clear, by the way the verifier should use ..

Why would I want to inject something into a `Configuration` class that I never use? All I need is a builder and the builder is so simple that I can have that provided by my DI Container or construct it manually.

**Comment by lcobucci** [comment]
@SamMousa we've tried to document the use cases of the `Configuration` object on https://lcobucci-jwt.readthedocs.io/en/stable/configuration/. It's definitely not a mandatory component but my experience with users on the previous versions led us to create and suggest it - not everyone is familiar with or uses a DI container (unfortunately).

In terms of design, well, it's a service locator. I'm yet to find a service locator that isn't terrible.
What we've **tried** to do is to keep the nastiness contained there, that's why it has a high efferent coupling and low afferent coupling.

I'd be delighted to merge a PR from that clarifies things on the documentation or that improves the design of the lib :+1:
