### ISSUE TITLE
How to update the expiration time of token?

### ISSUE THREAD

**Issue by hujinchen** [lcobucci/jwt#622]

**Comment by Ocramius** [comment]
A token that has been generated cannot be modified anymore: you can change the expiration time before generating a token:

https://github.com/lcobucci/jwt/blob/43cb7a704c50abd37942651825c6195cf12b5278/src/Builder.php#L22-L25

**Comment by hujinchen** [comment]
> A token that has been generated cannot be modified anymore: you can change the expiration time before generating a token:
> 
> https://github.com/lcobucci/jwt/blob/43cb7a704c50abd37942651825c6195cf12b5278/src/Builder.php#L22-L25

I know. Is there a way to update the token?

**Comment by lcobucci** [comment]
@hujinchen no, a token is immutable because it's usually sent over to multiple places/services/clients. That's why expiring tokens is a good practice, otherwise, undesired users would be able to exploit your application in case of a leaked token.

What you should do instead is issuing a new token.

**Comment by hujinchen** [comment]
@lcobucci Hello, now there is a requirement that when a user logs out and logs in again, should the old token be discarded and no longer be used?

In this case, I don't care about the old token?

**Comment by Ocramius** [comment]
There is no "log out" with tokens: if you send the token with a request, that is your authentication, and if you don't, you are not authenticated

**Comment by hujinchen** [comment]
@Ocramius This is OK. What I want to know is how to deal with the old token? Or do you not need to process, just verify the token carried by this request?

For example, the token expiration time I set is 7 days. When the user logs in repeatedly, n tokens will be generated.

In this way, the old token has not expired yet. When the user uses the old token to make a request by illegal means, won't the request succeed?

**Comment by Ocramius** [comment]
> In this way, the old token has not expired yet. When the user uses the old token to make a request by illegal means, won't the request succeed?

The old tokens are all valid until the 7 days are past: this is part of the design of JWT tokens (general concept) in first place. If you don't want this, then JWT tokens are not the solution that you are looking for.

**Comment by hujinchen** [comment]
@Ocramius 好的，了解。 谢谢哈！

**Comment by hujinchen** [comment]
@Ocramius OK, I understand. Thank you!

**Comment by vudaltsov** [comment]
I think the question is: how to create a new token with same claims but with a new expiration date. In other words how to create a new prolonged token.

**Comment by lcobucci** [comment]
> I think the question is: how to create a new token with same claims but with a new expiration date. In other words how to create a new prolonged token.

Then the answer would be: not a concern for this library 😄

It shouldn't be only the expiration date that would be "refreshed", the library would also have to update the issue date and the not before date.

Folks can create a new builder and populate it with the new values as they want, especially because the definition on how to perform such task isn't something abstract or standardised.

What we also provide is a way to inject the factory responsible for creating Builder. So, if someone wants to have default claims for their app to be filled in, they are able to provide their own factories and pre-configure stuff as needed - reducing the amount of claims to configure while issuing (or prolonging) tokens.
