### ISSUE TITLE
change order $headers

### ISSUE THREAD

**Issue by obione94** [lcobucci/jwt#723]
hey, Luis
how can I change the order of the headers
`private array $headers = ['typ' => 'JWT', 'alg' => null];`
to
[ 'alg' => null,'typ' => 'JWT']
for example
i cant find setHeaders method or removeHeaders
thk Luis.

**Comment by lcobucci** [comment]
@obione94 that's indeed not exposed to end-users. Why do you need it?

**Comment by obione94** [comment]
hey @lcobucci  , thk for your reactivity,
because the headers crimping is not the same depending on the position 
['typ' => 'JWT', 'alg' => Sha256]
=> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
['alg' => Sha256,'typ' => 'JWT']
=> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
and for the other case a need only 
['alg' => Sha256]
it was cool if can't removeHeader (<> withHeader)

**Comment by lcobucci** [comment]
Although, the `typ` header isn't mandatory we enforce it [here](https://github.com/lcobucci/jwt/blob/4.2.x/src/Token/Builder.php#L21) because the RFC states that as a recommended practice. So, all tokens issued by this lib have it.

We also enforce the order of the two headers on that line, btw, which should give a consistent encoded value.

Our parsing shouldn't be affected by the cases you provided (everything should just work).

That's something that I don't want to change on the lib because I don't see a strong reason to do so.
However, if you have this need you may implement a custom builder that allows for that and, if needed, inject its factory on the configuration object  :+1:

**Comment by obione94** [comment]
Ok I'm doing a class by adding a little setHeader, thank you for your speed @lcobucci you are awesome loool ;)
