### ISSUE TITLE
Incomplete instructions for setting validation constraints?

### ISSUE THREAD

**Issue by NicolasCARPi** [lcobucci/jwt#767]
Hello,

When looking at the Validating tokens part of the doc, one cannot find the `setValidationConstraints()` function call. The code shows `$constraints = $config->validationConstraints();` but this is empty if no constraints have been set beforehand with this function.

One has to look into the source code or the customization part of the doc to find that this exists.

Did I miss something or can I send a patch for the doc?

BTW, thanks for this lib, it is really well made :+1: !

**Comment by lcobucci** [comment]
@NicolasCARPi we've tried to segregate configuration for usage, that's why the samples on validation use a pre-existing configuration object. We briefly mention the configuration here: https://lcobucci-jwt.readthedocs.io/en/stable/configuration/#customisation.

Feel free to send us a patch to improve things if you have suggestions :)
