### ISSUE TITLE
Nested JWT's ? It supports or will support? It is possible to create one right now?

### ISSUE THREAD

**Issue by nunovieira93** [lcobucci/jwt#79]
Hi guys. Thanks for this Lib, its really great, i love how it works.

But, i want to know if you guys will ever make a **Nested JWT** (**JWS** inside a **JWE**) like in this post: [signed-and-encrypted-jwt](http://connect2id.com/products/nimbus-jose-jwt/examples/signed-and-encrypted-jwt).

With the lib how its right now, it is possible to make a Nested JWT ? Maybe with custom code?

Thanks!

**Comment by lcobucci** [comment]
Thanks @nunovieira93, it's good to have this nice feedback :smile:

We're slowly working on the next major release and #6 will solve that need - but we don't have any idea about when it will be released :disappointed:.

I'm still thinking about the best way to implement it (probably will be a different repo since my ideia is to let people download just what they really want/need).

**Comment by nunovieira93** [comment]
Oh ok, thanks for the fast reply ! :smile: 

I'll be waiting for that release then. Good Luck!

**Comment by lcobucci** [comment]
Awesome @nunovieira93! I'll mark this as a duplication of #6 and close it :wink:
