### ISSUE TITLE
JWT Token to builder

### ISSUE THREAD

**Issue by geggleto** [lcobucci/jwt#96]
For the new version would it be possible to make it easier to turn a Token back into a Builder ?

Example, I am trying to write a Middleware that uses JWT to manage application state [basically replacing native sessions], and while the Parser gives back a Token, Tokens are immutable, which leaves me to having to do a bunch of hackish things... it would be best if Tokens were not immutable and had setter methods or a way to modify their state.

...  dirty hack current: https://gist.github.com/geggleto/4c90a4037580bc5a128a5184e37a8cc0

**Comment by schnittstabil** [comment]
@geggleto Interesting idea, however, I can't image how to do that with middlewares, and how mutability would help.

Especially, the `ResponseInterface` doesn't have a `withAttribute` method–or similar!?

**Comment by geggleto** [comment]
Hey Mike,

https://gist.github.com/geggleto/4c90a4037580bc5a128a5184e37a8cc0
withAttribute on ServerRequest... the problem is having to take the Token
and reinsert into the Builder in order to modify a token once created.

**Comment by lcobucci** [comment]
When I was designing the first version of this lib I thought about something like `Builder::fromToken(Token $token):Builder` but I never had the need, even after playing with @Ocramius on [PSR7Session](https://github.com/Ocramius/PSR7Session)...

I still have mixed feelings on this... I mean, all the registered claims shouldn't be copied because it's just wrong IMHO (maybe just the `sub` would be ok but the others should be set on the code that is building the token).

**Comment by geggleto** [comment]
I am not sure I understand, the Web Token in the spec does not mention it being immutable... So then it should be recreated after every request? basically a one-time-use token?

**Comment by lcobucci** [comment]
@geggleto the RFC don't say anything about state and requests because it's not in the scope of it (IMO).

A JWT is just a compact representation of some data and if we generate a token with the exact same data the output will be the same (the signature may change depending on the algorithm you use ofc).

What I'm trying to explain is that there's no reason to copy claims like `aud`, `iss`, `exp`, `iat`, `nbf` and `jti` because they belong to a different token:

* `iss`: you're the issuer so just your identification should be the only valid value;
* `aud`: you should always provide to ensure that no token will be used by unauthorized clients;
* `iat`: since you're creating a new one it shouldn't be copied;
* `exp`: this should be X seconds after `iat` (and current time) otherwise you would issue expired tokens;
* `nbf`: this should be `iat` <= `nbf` < `exp` and probably the copied timestamp would be in the past (which means it would be just useless info);
* `jti`: that's the token identifier so every token should have a different value.

**Comment by lcobucci** [comment]
@geggleto did you had time to think about my last comment? Do you have any other argument in favor of creating a token from another one?

**Comment by geggleto** [comment]
I worked around the issues I had ;)

**Comment by lcobucci** [comment]
Yes, but we were discussing about the need of implementing this. Do you still think it is relevant or do you agree with the things I said (that we shouldn't "clone" those claims)?

(just want to know to give this issue a closure 😛 )

**Comment by geggleto** [comment]
Idk, I'm stuck philosophically about it.

My use case is that, I want to use THE same token more than once... but as you pointed out that might not be the intention of this library. :)

**Comment by lcobucci** [comment]
Right, but if you need **the same token** you don't need to pass through the whole token building process again (specially the signing part), since you have the original object and you could just use `(string) $token`.

Anyway, we can discuss a bit more on [gitter](https://gitter.im/lcobucci/jwt) if you're willing to, thanks! 😄

**Comment by schnittstabil** [comment]
@geggleto I've just found [Ocramius/PSR7Session](https://github.com/Ocramius/PSR7Session), looks like it's already done :heart_eyes:
